class mac_generator;
    mailbox #(mac_transaction) drv_mbx;
    event done;
    int num_txns;
    function new(mailbox #(mac_transaction) mbx, int count = 50);
        this.drv_mbx  = mbx;
        this.num_txns = count;
    endfunction
    task run();
        mac_transaction txn;
        int count = 0;
        $display("[%0t] GEN: Starting directed + random stimulus (%0d total)", $time, num_txns);
        txn = new();
        txn.operand_a = 64'd5;
        txn.operand_b = 64'd3;
        txn.mode      = 2'b00;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b1;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'd0;
        txn.operand_b = 64'hFFFF_FFFF_FFFF_FFFF;
        txn.mode      = 2'b00;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b1;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'd1;
        txn.operand_b = 64'd1;
        txn.mode      = 2'b00;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b1;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'hFFFF_FFFF_FFFF_FFFF;
        txn.operand_b = 64'hFFFF_FFFF_FFFF_FFFF;
        txn.mode      = 2'b00;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b1;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'd10;
        txn.operand_b = 64'd20;
        txn.mode      = 2'b01;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b1;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'd30;
        txn.operand_b = 64'd40;
        txn.mode      = 2'b01;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b0;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'hFFFF_FFFF_FFFF_FFFF;
        txn.operand_b = 64'hFFFF_FFFF_FFFF_FFFF;
        txn.mode      = 2'b10;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b1;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'hFFFF_FFFF_FFFF_FFFF;
        txn.operand_b = 64'hFFFF_FFFF_FFFF_FFFF;
        txn.mode      = 2'b10;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b0;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'd100;
        txn.operand_b = 64'd200;
        txn.mode      = 2'b11;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b1;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = 128'd997;
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'd7;
        txn.operand_b = 64'd8;
        txn.mode      = 2'b01;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b1;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'd15;
        txn.operand_b = 64'd16;
        txn.mode      = 2'b00;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b1;
        txn.stall     = 1'b1;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        txn = new();
        txn.operand_a = 64'd15;
        txn.operand_b = 64'd16;
        txn.mode      = 2'b00;
        txn.mac_en    = 1'b1;
        txn.clear_acc = 1'b1;
        txn.stall     = 1'b0;
        txn.flush     = 1'b0;
        txn.modulus   = {128{1'b1}};
        drv_mbx.put(txn);
        count++;
        while (count < num_txns) begin
            txn = new();
            assert(txn.randomize()) else $error("GEN: Randomization failed");
            drv_mbx.put(txn);
            count++;
        end
        $display("[%0t] GEN: Done — %0d transactions generated", $time, count);
        -> done;
    endtask
endclass
